In [1]:
import torch
import torchvision
import torchvision.transforms as transforms

In [2]:
# Weird behaviour when using two dataloaders:
# We create two dataloaders, one with some batch_size and the other one with batch size = length of train set, such that no RNG is needed
# However, it turns out that even in this case an RNG state is occupied, so we should not expect the same randomness

batch_size = 20

torch.manual_seed(123456)

transform = transforms.Compose([transforms.ToTensor()])

In [3]:
#image datasets
trainset = torchvision.datasets.MNIST('dataset/',
                                              train=True,
                                              download=True,
                                              transform=transform)
# first dataloader
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                              shuffle=True, num_workers=2)

In [4]:
# just to be sure, reset seed
# show first batch

torch.manual_seed(123456)

inputs, classes = next(iter(trainloader))
print(classes)

tensor([8, 7, 6, 5, 8, 1, 7, 4, 9, 1, 5, 4, 2, 0, 0, 4, 0, 0, 9, 5])


In [9]:
# reset seed and define second dataloader
torch.manual_seed(123456)

# second dataloader without shuffling (still uses RNG state)
data_samp = torch.utils.data.DataLoader(
                trainset,
                batch_size=len(trainset))

In [10]:
# creating a second dataloader doesn't change the rng state

inputs, classes = next(iter(trainloader))
print(classes)

tensor([8, 7, 6, 5, 8, 1, 7, 4, 9, 1, 5, 4, 2, 0, 0, 4, 0, 0, 9, 5])


In [11]:
# but referencing it does

torch.manual_seed(123456)

random_name = list(data_samp)

inputs, classes = next(iter(trainloader))
print(classes)

tensor([6, 7, 0, 1, 8, 9, 9, 7, 0, 2, 1, 8, 3, 6, 6, 8, 6, 7, 0, 3])
